[package]
name = "dockerfile-roast"
version = "1.4.13"
edition = "2021"
description = "A Dockerfile linter with personality — catches bad practices with snarky, funny error messages"
license = "MIT"
repository = "https://github.com/immanuwell/dockerfile-roast"
homepage = "https://github.com/immanuwell/dockerfile-roast"
readme = "README.md"
keywords = ["dockerfile", "linter", "docker", "cli"]
categories = ["command-line-utilities", "development-tools"]
include = ["/src/**", "/tests/**", "/examples/**", "/schemas/**", "/Cargo.toml", "/Cargo.lock", "/build.rs", "/README.md", "/DOCS.md", "/LICENSE"]

[lib]
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "droast"
path = "src/main.rs"

[dependencies]
clap = { version = "4", features = ["derive", "color"] }
colored = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
glob = "0.3"
regex = "1"
anyhow = "1"
toml = { version = "0.8", default-features = false, features = ["parse"] }
clap_complete = "4"

[target.'cfg(not(all(target_arch = "wasm32", target_os = "unknown")))'.dependencies]
dotenvy = "0.15.7"
hcl-rs = "0.19.7"
ignore = "0.4"
serde_yaml = "0.9.34"
semver = "1"
spdx = "0.10"
time = { version = "0.3", features = ["parsing"] }
sha2 = "0.10"

[target.'cfg(all(target_arch = "wasm32", target_os = "unknown"))'.dependencies]
wasm-bindgen = "0.2"
