[package]
name = "immanuwell/droast"
version = "1.5.0" # droast:release-version
description = "A fast Dockerfile linter with practical security, correctness, and build-quality checks."
license = "MIT"
readme = "README.md"
repository = "https://github.com/immanuwell/dockerfile-roast"
homepage = "https://ewry.net/droast-dockerfile-linter/"
entrypoint = "droast"

[[module]]
name = "droast"
source = "target/wasm32-wasip1/release/droast.wasm"

[[command]]
name = "droast"
module = "droast"
runner = "wasi"
